apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "helmer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "helmer.serviceAccountName" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }} 
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
